#!/bin/bash
set -e
branch="master"

echo
echo -n "Install to (relative/absolute path)(defaults to '~/.mybash.d'): "
read MYBASH_DIR
# if input is null, use default
[ -z $MYBASH_DIR ] && MYBASH_DIR="$HOME/.mybash.d" ; eval MYBASH_DIR=$MYBASH_DIR

# if directory exists, delete it
if [ -e $MYBASH_DIR ]; then
	echo -n "WARNING: Directory already exists. Contents will be deleted. Continue? (y/n): "
	read dir_cont
	if [ "$dir_cont" == "y" ]; then
		echo "Deleting $MYBASH_DIR..."
		rm -r -f $MYBASH_DIR
	elif [ "$dir_cont" == "n" ]; then
		echo "Exiting..."
		exit 1
	else
		echo "ERROR: input not y/n"
		exit 2
	fi
fi

# create directory & all parents
mkdir -p $MYBASH_DIR
# download and untar all in one
echo "Downloading & extracting..."
curl -L -s https://api.github.com/repos/raehik/mybash/tarball/$branch | tar -zxC $MYBASH_DIR --strip-components=1
echo "Extracted to $MYBASH_DIR"

echo "Backing up .bashrc to .bashrc.bak..."
cp $HOME/.bashrc $HOME/.bashrc.bak

echo "Adding environment variable MYBASH_DIR in ~/.bashrc..."
echo "MYBASH_DIR=$MYBASH_DIR" >> $HOME/.bashrc

echo "Sourcing $MYBASH_DIR/main in ~/.bashrc..."
echo ". \$MYBASH_DIR/main" >> $HOME/.bashrc

echo "Install complete. Running 'exec bash'..."
exec bash
