#!/bin/bash

branch="master"

echo -n "Install directory (defaults to '~/.mybash.d'): "
read MYBASH_DIR
[ -z $MYBASH_DIR ] && MYBASH_DIR="${HOME}/.mybash.d" # if input empty, use default
[[ ! $MYBASH_DIR == /* ]] && MYBASH_DIR="$(pwd)/${MYBASH_DIR}" # if input is relative, add on the pwd
# be careful and verbose about directory
if [ -e $MYBASH_DIR ]; then	# if is existing dir
	echo -n "Warning: Directory already exists. Contents will be deleted. Continue? (y/n): "
	read dir_cont
	if [ "$dir_cont" == "y" ] || [ "$dir_cont" == "Y" ]; then
		echo "Deleting ${MYBASH_DIR}..."
		rm -r ${MYBASH_DIR}
	elif [ "$dir_cont" == "n" ] || [ "$dir_cont" == "N" ]; then
		echo "Exiting..."
		exit 1
	else
		echo "Error: Your input was not y/n (was ${dir_cont})"
		exit 1
	fi
fi

# download and untar
echo "Downloading..."
curl -L -s https://api.github.com/repos/raehik/mybash/tarball/${branch} | tar -zx -C /tmp
mv /tmp/raehik-mybash-* ${MYBASH_DIR}
echo "Extracted and moved to ${MYBASH_DIR}"

# backup .bashrc because we are overly careful
echo "Backing up .bashrc to .bashrc.bak..."
cp ${HOME}/.bashrc ${HOME}/.bashrc.bak

# append sourcing line
echo "Appending '. ${MYBASH_DIR}/main' into ~/.bashrc... (later make this work for all shells)"
echo ". ${MYBASH_DIR}/main" >> ${HOME}/.bashrc # later, the filename will depend on the shell you choose (it should then ask to check that your .(shell)rc is what I think it is)

echo "Install complete. Restart your shell by logging out and in (if you're in console mode) or starting a new terminal."
