#!/bin/bash

# This is the controller file for the different options you may use for bash.
# From here, such options can be enabled and disabled separately with ease.
# Please update this file if you add any new option files!

. ~/.mybash.d/prompt
mybash_prompt

. ~/.mybash.d/aliases
