#!/bin/bash

function usage {
	echo "Usage: $0 conf_to_enable"
	if [ $# -eq 0 ]; then
		exit 99
	else
		exit $1
	fi
}

function mybash-enconf {
	echo "Your choices are:"
	for conf in ${MYBASH_DIR}/confs-available/*.conf; do
		conf="$(basename "$conf")"
		confname="${conf%.conf}"
		echo -n " $confname"
	done
	echo
	echo "Which configs do you want to enable (wildcards & multiple ok)?"
	echo -n "> "
	read choices
	echo "Lots of checks here. choices = ${choices}.conf"
}
