#!/bin/bash

function mybash-refresh-aliases() {
alias u='cd ..' # go up 1 level

# colour ls and grep by default if available
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# set command-line editing to vi mode
set -o vi
}
mybash-refresh-aliases
