#!/bin/bash

function mybash-refresh-prompt {
. ${MYBASH_DIR}/.colours # source readable colours

# Default colour scheme if there isn't one for the current hostname
col_name=${dark}${grn}
col_at=${dark}${grn}
col_host=${dark}${grn}
col_colon=${dark}${grn}
col_pwd=${lght}${blu}
col_prompt=${lght}${red}

# maple-ubuntu
if [ $(hostname) == "maple-ubuntu" ]; then
	col_name=${dark}${grn}
	col_at=${dark}${grn}
	col_host=${dark}${grn}
	col_colon=${dark}${grn}
	col_pwd=${lght}${blu}
	col_prompt=${lght}${red}
fi

# SRV1-ZIPPY
if [ $(hostname) == "SRV1-ZIPPY" ]; then
	col_name=${dark}${grn}
	col_at=${dark}${grn}
	col_host=${dark}${grn}
	col_colon=${dark}${grn}
	col_pwd=${lght}${blu}
	col_prompt=${lght}${red}
fi

# This changes all COL_ variables except COL_PWD to ${dark}${red} when logged
# on as root user (with any hostname)
if [ $EUID -eq "0" ]
  then
  col_name=${dark}${red}
  col_at=${dark}${red}
  col_host=${dark}${red}
  col_colon=${dark}${red}
  col_prompt=${dark}${red}
fi

# DON'T CHANGE THIS: it depends fully on the COL_ variables.
PS1="${col_name}\u${col_at}@${col_host}\h${col_colon}:${col_pwd}\${PWD}${col_prompt}\\$ ${none}"
}
mybash-refresh-prompt
